[package]
name = "ask"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "ask"
path = "src/main.rs"

[dependencies]
closedshell-lib = { path = "../closedshell-lib" }
clap = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
